### ISSUE TITLE
having trouble updating

### ISSUE THREAD

**Issue by DrkVengeance** [teknogods/TeknoParrotUI#516]
![Screenshot (1)](https://github.com/teknogods/TeknoParrotUI/assets/142958556/08f68ed6-988e-474b-921a-a9e6b1035384)
![Screenshot (2)](https://github.com/teknogods/TeknoParrotUI/assets/142958556/1345426f-0317-4744-94d8-6955ce3f4cc2)

**Comment by mame-rr-player001** [comment]
me too.
exception.txt says as below
---------------------------
System.IO.IOException: 別のプロセスで使用されているため、プロセスはファイル 'E:\Game\Arcade\TeknoParrot\TeknoParrotUI-master\bin\x86\Release\libs\CefSharp\icudtl.dat' にアクセスできません。
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at TeknoParrotUi.Views.DownloadControl.<>c__DisplayClass11_0.<DoComplete>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Boomslangnz** [comment]
Yes there was an issue if you were on a specific version which prevents being able to update correctly, please download latest TeknoParrot UI update manually which resolves this going forward

https://github.com/teknogods/TeknoParrotUI/releases
