### ISSUE TITLE
update exception

### ISSUE THREAD

**Issue by mame-rr-player001** [teknogods/TeknoParrotUI#611]
Hi, I faced teknoparrot online update as below.
(exception.txt)

What should I do?
----------------------------------------------------

System.IO.InvalidDataException: 中央ディレクトリの終わりレコードが見つかりません。
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at TeknoParrotUi.Views.DownloadControl.<>c__DisplayClass11_0.<DoComplete>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Boomslangnz** [comment]
please download latest TeknoParrot UI update manually and copy to TeknoParrot folder

https://github.com/teknogods/TeknoParrotUI/releases
