### ISSUE TITLE
Can not update from 1.0.0.1149 to higher version

### ISSUE THREAD

**Issue by YanjunLiu2** [teknogods/TeknoParrotUI#629]
System.IO.InvalidDataException: 找不到中央目录结尾记录。
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at TeknoParrotUi.Views.DownloadControl.<>c__DisplayClass11_0.<DoComplete>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by YanjunLiu2** [comment]
All my friends met the same issue.

**Comment by Nezarn** [comment]
Update TPUI manually https://github.com/teknogods/TeknoParrotUI/releases
